version: '3.4'

services:
  fiskalapp:
    image: ${DOCKER_REGISTRY-}fiskalapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:443"
    environment:
      AppSettings__Secret: "MOJAMAMASUNCEMILO"
      AppSettings__FiskalScheduler :  "0 * * * *"
      AppSettings__ReportScheduler :  "15 21 * * *"
      AppSettings__Mail :  "vladimir.mercep@gmail.com"
      AppSettings__Password :  "Vl4d1m1rM3rc3p"
      AppSettings__Connection : "server=192.168.5.27;port=3306;database=wending_machine;user=root;password=;CharSet=utf8"
      ConnectionStrings__DefaultConnection: "server=192.168.5.27;port=3306;database=wending_machine;user=root;password=;CharSet=utf8"
      TZ: "Europe/Zagreb" 
